# Generated by Django 5.2.17 on 2026-08-14 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_organizationmember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Report"),
                            ("finance", "Finance Report"),
                            ("custom", "Custom Report"),
                        ],
                        default="sales",
                        max_length=20,
                        verbose_name="Report type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("collecting_data", "Collecting Data"),
                            ("calling_ai", "Calling AI"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="Period start")),
                ("period_end", models.DateTimeField(verbose_name="Period end")),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Собранные бизнес-метрики в формате JSON",
                        verbose_name="Collected metrics",
                    ),
                ),
                (
                    "ai_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Ответ от AI в формате JSON",
                        verbose_name="AI response",
                    ),
                ),
                (
                    "generated_text",
                    models.TextField(
                        blank=True,
                        help_text="Сгенерированный текст отчёта",
                        verbose_name="Generated text",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Текст ошибки, если генерация не удалась",
                        verbose_name="Error",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/pdf/%Y/%m/",
                        verbose_name="PDF file",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Completed at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"], name="reports_rep_organiz_ae5072_idx"
                    ),
                    models.Index(
                        fields=["organization", "report_type"],
                        name="reports_rep_organiz_bdc0af_idx",
                    ),
                    models.Index(fields=["created_at"], name="reports_rep_created_a6aabf_idx"),
                ],
            },
        ),
    ]
