# Generated by Django 5.2.17 on 2026-08-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="generated_html",
            field=models.TextField(
                blank=True, help_text="HTML версия отчёта", verbose_name="Generated HTML"
            ),
        ),
    ]
