# Generated by Django 5.2.17 on 2026-08-18 06:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organizationmember"),
        ("reports", "0002_report_generated_html"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Report"),
                            ("finance", "Finance Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                        verbose_name="Тип отчёта",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Частота генерации",
                    ),
                ),
                (
                    "run_at_hour",
                    models.PositiveIntegerField(
                        default=9,
                        help_text="Час дня в UTC (0-23)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                        verbose_name="Час запуска (UTC)",
                    ),
                ),
                (
                    "run_at_minute",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Минута часа (0-59)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                        verbose_name="Минута запуска (UTC)",
                    ),
                ),
                (
                    "run_day_of_week",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0=Пн, 1=Вт, ..., 6=Вс",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="День недели (для weekly)",
                    ),
                ),
                (
                    "run_day_of_month",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="День месяца (1-28)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                        verbose_name="День месяца (для monthly)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последний запуск"),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Следующий запуск"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание отчётов",
                "verbose_name_plural": "Расписания отчётов",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "next_run_at"], name="reports_rep_is_acti_c0e6a8_idx"
                    ),
                    models.Index(
                        fields=["organization", "frequency"], name="reports_rep_organiz_e77db3_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "report_type", "frequency"),
                        name="unique_schedule_per_org_report_frequency",
                    )
                ],
            },
        ),
    ]
