# Generated by Django 5.2.17 on 2026-08-21 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_reportschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="reports/pdf/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"], message="Только PDF файлы разрешены."
                    )
                ],
                verbose_name="PDF file",
            ),
        ),
    ]
