# Generated by Django 5.2.17 on 2026-08-17 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0002_report_generated_html"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                        verbose_name="Канал доставки",
                    ),
                ),
                ("recipient", models.CharField(max_length=500, verbose_name="Получатель")),
                (
                    "subject",
                    models.CharField(blank=True, default="", max_length=500, verbose_name="Тема"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("success", "Отправлено успешно"),
                            ("failed", "Ошибка отправки"),
                            ("retrying", "Повторная попытка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_details",
                    models.TextField(blank=True, default="", verbose_name="Детали ошибки"),
                ),
                (
                    "notification_id",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="ID уведомления"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Количество попыток"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Метаданные")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Отправлено")),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="reports.report",
                        verbose_name="Отчёт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог уведомления",
                "verbose_name_plural": "Логи уведомлений",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="notificatio_status_68c9bc_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="notificatio_user_id_a3de53_idx"
                    ),
                    models.Index(
                        fields=["report", "created_at"], name="notificatio_report__b59fce_idx"
                    ),
                ],
            },
        ),
    ]
