# Generated by Django 5.2.17 on 2026-08-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notifications Logs",
            },
        ),
    ]
