# Generated by Django 5.2.17 on 2026-08-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_data", "0001_initial"),
        ("organizations", "0002_organizationmember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Amount"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("RUB", "Russian Ruble"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                        ],
                        default="USD",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rent", "Rent"),
                            ("salary", "Salary"),
                            ("marketing", "Marketing"),
                            ("utilities", "Utilities"),
                            ("equipment", "Equipment"),
                            ("software", "Software"),
                            ("travel", "Travel"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("expense_date", models.DateTimeField(verbose_name="Expense date")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "expense",
                "verbose_name_plural": "expenses",
                "ordering": ["-expense_date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "category"], name="business_da_organiz_1fa862_idx"
                    ),
                    models.Index(
                        fields=["organization", "expense_date"],
                        name="business_da_organiz_428184_idx",
                    ),
                ],
            },
        ),
    ]
